name: terraform

on:
  pull_request:
    paths:
      - "*.tf"
      - "environments/**"
      - ".github/workflows/terraform.yml"
  push:
    branches: ["main"]
    paths:
      - "*.tf"
      - "environments/**"
      - ".github/workflows/terraform.yml"
  workflow_dispatch:
    inputs:
      target_env:
        description: "Environment to apply"
        type: choice
        required: true
        options:
          - dev

permissions:
  contents: read

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_TOKEN_app_terraform_io: "${{ secrets.TF_API_TOKEN }}"
  TF_IN_AUTOMATION: "true"

jobs:
  plan:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev]
    environment: ${{ matrix.env }}
    env:
      TF_WORKSPACE: testcliworkspace
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Plan (Remote)
        if: github.event_name == 'pull_request' || inputs.target_env == matrix.env
        run: terraform plan -input=false -var-file="environments/${{ matrix.env }}/terraform.tfvars"

  apply:
    if:  github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev]
    environment: ${{ matrix.env }}
    env:
      TF_WORKSPACE: testcliworkspace
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Apply (Remote)
        if: github.event_name == 'push' || inputs.target_env == matrix.env
        run: terraform apply -auto-approve -input=false -var-file="environments/${{ matrix.env }}/terraform.tfvars"
